### ISSUE TITLE
GNU ld linker (2.25) requires '-lm'

### ISSUE THREAD

**Issue by mtds** [jhammond/xltop#6]
Hello.

Apparently the ld linker which comes with GNU binutils version 2.25
has become more 'demanding' but I cannot find exactly the reason.

During the linking phase I got the following error:
```
/usr/bin/ld: x_node.o: undefined reference to symbol 'expm1@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I have fixed it adding '-lm' to all the xltop{clusd,master,servd}_LDADD defined
in the src/Makefile (generated by configure).

I am not sure if there's another solution other than adding this '-lm' to
Makefile.am, in order to avoid the additional step of adding it by yourself
to the generated Makefile.

Regards,
Matteo

**Comment by jhammond** [comment]
It should be enough just to add it to xltop_master_LDADD in src/Makefile.am.

**Comment by mtds** [comment]
Yep, that do the trick but I believe xltop_master_LDADD is not sufficient.
I have modified all the declarations in the file:
```
xltop_LDADD = -lcurl -lev -lncurses -lm
xltop_clusd_LDADD = -lcurl -lev -lm
xltop_master_LDADD = -lconfuse -lev -lncurses -lm
xltop_servd_LDADD = -lcurl -lev -lm
```
otherwise the linker will still throws the same error while compiling the 
other xltop binaries.

**Comment by jhammond** [comment]
Yes. You're right.

**Comment by mtds** [comment]
I have tested it also on other versions of ld and the result is just fine.
Will you consider including these modifications into 'src/Makefile.am'
on the master branch?

If that it's the case then I will make a pull request.

Matteo

**Comment by jhammond** [comment]
Yes. I will include them.

**Comment by mtds** [comment]
Ok, I have just submitted a PR.

**Comment by jhammond** [comment]
Merged.
